# CMAKE generated file: DO NOT EDIT!
# Generated by "NMake Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

!IF "$(OS)" == "Windows_NT"
NULL=
!ELSE
NULL=nul
!ENDIF
SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = d:\Programy\CMake2.8\bin\cmake.exe

# The command to remove a file.
RM = d:\Programy\CMake2.8\bin\cmake.exe -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = d:\Programy\CMake2.8\bin\cmake-gui.exe

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = H:\Projekty\config4cpp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = H:\Projekty\config4cpp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	d:\Programy\CMake2.8\bin\cmake-gui.exe -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache\fast: edit_cache
.PHONY : edit_cache\fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	d:\Programy\CMake2.8\bin\cmake.exe -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache\fast: rebuild_cache
.PHONY : rebuild_cache\fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	d:\Programy\CMake2.8\bin\ctest.exe --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test\fast: test
.PHONY : test\fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start H:\Projekty\config4cpp\CMakeFiles H:\Projekty\config4cpp\CMakeFiles\progress.marks
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) all
	$(CMAKE_COMMAND) -E cmake_progress_start H:\Projekty\config4cpp\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) clean
.PHONY : clean

# The main clean target
clean\fast: clean
.PHONY : clean\fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall\fast:
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) preinstall
.PHONY : preinstall\fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named config2cpp

# Build rule for target.
config2cpp: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) config2cpp
.PHONY : config2cpp

# fast build rule for target.
config2cpp\fast:
	$(MAKE) -f src\CMakeFiles\config2cpp.dir\build.make /nologo -$(MAKEFLAGS) src\CMakeFiles\config2cpp.dir\build
.PHONY : config2cpp\fast

#=============================================================================
# Target rules for targets named config2cpp-nocheck

# Build rule for target.
config2cpp-nocheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) config2cpp-nocheck
.PHONY : config2cpp-nocheck

# fast build rule for target.
config2cpp-nocheck\fast:
	$(MAKE) -f src\CMakeFiles\config2cpp-nocheck.dir\build.make /nologo -$(MAKEFLAGS) src\CMakeFiles\config2cpp-nocheck.dir\build
.PHONY : config2cpp-nocheck\fast

#=============================================================================
# Target rules for targets named config4cpp

# Build rule for target.
config4cpp: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) config4cpp
.PHONY : config4cpp

# fast build rule for target.
config4cpp\fast:
	$(MAKE) -f src\CMakeFiles\config4cpp.dir\build.make /nologo -$(MAKEFLAGS) src\CMakeFiles\config4cpp.dir\build
.PHONY : config4cpp\fast

#=============================================================================
# Target rules for targets named config4cpp.exe

# Build rule for target.
config4cpp.exe: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) config4cpp.exe
.PHONY : config4cpp.exe

# fast build rule for target.
config4cpp.exe\fast:
	$(MAKE) -f src\CMakeFiles\config4cpp.exe.dir\build.make /nologo -$(MAKEFLAGS) src\CMakeFiles\config4cpp.exe.dir\build
.PHONY : config4cpp.exe\fast

#=============================================================================
# Target rules for targets named extended-schema-validator

# Build rule for target.
extended-schema-validator: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) extended-schema-validator
.PHONY : extended-schema-validator

# fast build rule for target.
extended-schema-validator\fast:
	$(MAKE) -f demos\extended-schema-validator\CMakeFiles\extended-schema-validator.dir\build.make /nologo -$(MAKEFLAGS) demos\extended-schema-validator\CMakeFiles\extended-schema-validator.dir\build
.PHONY : extended-schema-validator\fast

#=============================================================================
# Target rules for targets named log-level

# Build rule for target.
log-level: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) log-level
.PHONY : log-level

# fast build rule for target.
log-level\fast:
	$(MAKE) -f demos\log-level\CMakeFiles\log-level.dir\build.make /nologo -$(MAKEFLAGS) demos\log-level\CMakeFiles\log-level.dir\build
.PHONY : log-level\fast

#=============================================================================
# Target rules for targets named recipes

# Build rule for target.
recipes: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) recipes
.PHONY : recipes

# fast build rule for target.
recipes\fast:
	$(MAKE) -f demos\recipes\CMakeFiles\recipes.dir\build.make /nologo -$(MAKEFLAGS) demos\recipes\CMakeFiles\recipes.dir\build
.PHONY : recipes\fast

#=============================================================================
# Target rules for targets named test-schema-types

# Build rule for target.
test-schema-types: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) test-schema-types
.PHONY : test-schema-types

# fast build rule for target.
test-schema-types\fast:
	$(MAKE) -f tests\schema-types\CMakeFiles\test-schema-types.dir\build.make /nologo -$(MAKEFLAGS) tests\schema-types\CMakeFiles\test-schema-types.dir\build
.PHONY : test-schema-types\fast

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... test
	@echo ... config2cpp
	@echo ... config2cpp-nocheck
	@echo ... config4cpp
	@echo ... config4cpp.exe
	@echo ... extended-schema-validator
	@echo ... log-level
	@echo ... recipes
	@echo ... test-schema-types
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

